### ISSUE TITLE
Scripts loading twice as they're not being dequeued.

### ISSUE THREAD

**Issue by EiraStudios** [wp-id/hyperdrive#26] opened 2017-05-11 04:27 UTC
I've tested this on several custom themes and Twenty Seventeen & Poseidon.

`calibrate_thrusters()` doesn't seem to successfully dequeue the scripts it's loading (like jquery, jquery migrate etc). It looks like it's because these are being enqueued after Hyperdrive hooks into `wp_head` so to fix this we would need to hook into `wp_print_scripts`, which is the last hook called before the scripts are rendered to the header.

Switching to this hook fixes the scripts not being dequeued but then another issue crops up with jQuery Migrate always finishes loading before jQuery Core does which results in _`"jQuery not defined error"`_.

I've fixed both issues and made another couple of minor changes in PR: #27

**Comment by jhabdas** [comment] 2017-05-11 04:43
Duplicate of https://github.com/wp-id/hyperdrive/issues/16

**Closed** 2017-05-11 09:35 UTC

**Comment by jhabdas** [comment] 2017-06-10 08:04
Root cause addressed as described here with sample waterfall: https://github.com/comfusion/hyperdrive/issues/7#issuecomment-307549870
